name: Deploy to PyPI Test on Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine semversion click
      
    - name: Update version
      run: |
        python -m semversion minor
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .version
        git commit -m "Update version [skip ci]"
      working-directory: ${{ github.workspace }}

    - name: Build and deploy to PyPI Test
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}